### ISSUE TITLE
Confusing error message when running in TravisCI 

### ISSUE THREAD

**Issue by maximelafarie** [codacy/node-codacy-coverage#54]
### node.js Version 9.7.1

I ran Codacy coverage on TravisCI to test the coverage of an Angular library. 

I run into the following error:
```
0.92s$ cat coverage/lcov.info | codacy-coverage --username 'maximelafarie' --projectName 'ngx-smart-modal'
[error] "2018-03-06T15:18:54.987Z"  'Status Code [404] - Error [{"error":"not found"}]'
[error] "2018-03-06T15:18:54.993Z"  'Error sending coverage'
[error] "2018-03-06T15:18:54.993Z"  Error: Expected Successful Status Code, but got [404]
    at /home/travis/.nvm/versions/node/v9.7.1/lib/node_modules/codacy-coverage/lib/reporter.js:109:23
    at tryCatcher (/home/travis/.nvm/versions/node/v9.7.1/lib/node_modules/codacy-coverage/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/.nvm/versions/node/v9.7.1/lib/node_modules/codacy-coverage/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/travis/.nvm/versions/node/v9.7.1/lib/node_modules/codacy-coverage/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/travis/.nvm/versions/node/v9.7.1/lib/node_modules/codacy-coverage/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/travis/.nvm/versions/node/v9.7.1/lib/node_modules/codacy-coverage/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/home/travis/.nvm/versions/node/v9.7.1/lib/node_modules/codacy-coverage/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/travis/.nvm/versions/node/v9.7.1/lib/node_modules/codacy-coverage/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/travis/.nvm/versions/node/v9.7.1/lib/node_modules/codacy-coverage/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:763:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate (timers.js:716:5)
```
Here's the full output: https://travis-ci.org/biig-io/ngx-smart-modal/builds/349861754
(Codacy error is located [line 2129](https://travis-ci.org/biig-io/ngx-smart-modal/builds/349861754#L2129))

The full .travis.yml file is located [here](https://github.com/biig-io/ngx-smart-modal/blob/master/.travis.yml)

I really don't know the origin of the error, given that the error message isn't very explicit and all works well with tools like codecov and codeclimate (the lcov file is successfully sent as the TravisCI job output shows).

**Comment by rtfpessoa** [comment]
Hi @maximelafarie,

From the error, seems like the token is either invalid or has no permissions.

After a quick check I was able to see that your account token count is 0.
For that reason, and since you are using the alternative way to authenticate (using the account token) you need to generate the token in [your account](https://app.codacy.com/account/apiTokens).

If you do not need an account token to send coverage and can you the project token.
You should be able to get it under `Project -> Settings -> Integrations -> Project API`, and like explained here https://github.com/codacy/node-codacy-coverage#usage you only need to export `CODACY_PROJECT_TOKEN`. Also if you start using the Project API token you do not need `--username` neither the `--projectName` since the token already identifies the project.

Let me know if it works.

**Comment by maximelafarie** [comment]
Thank you so much @rtfpessoa it works perfectly! 👌
