### ISSUE TITLE
Error sending jest coverage to enterprise codacy

### ISSUE THREAD

**Issue by ddieppa** [codacy/node-codacy-coverage#82]
# Error sending jest coverage to enterprise Codacy

### node.js Version
10.16.0
### Operating System
Windows 10

### Testing framework 
Jest

### Expected Behavior

I am trying to send the jest coverage to Codacy running this (Multiple variants)
1. ` jest --config .jestrc.js && codacy-coverage -e https://codacy.company.com:16006 --accountToken xxxxxxxx --username user --projectName project --verbose < src/scripts/tests/unit-test-coverage/lcov.info`
2. `jest --config .jestrc.js && codacy-coverage -e https://codacy.company.com:16006 --token xxxxxx --verbose < src/scripts/tests/unit-test-coverage/lcov.info`

Both variants fail with pretty much the same error

### Actual Behavior

Getting this error:

```
$  jest --config .jestrc.js && codacy-coverage --token xxxxxxxxxxxxx --verbose < src/scripts/tests/unit-test-coverage/lcov.info
 PASS   test  src/scripts/vuejs/store/modules/plan/__tests__/mutations.spec.js
 PASS   test  src/scripts/services/__tests__/Plan.service.spec.js
 PASS   test  src/scripts/services/__tests__/browseApi.service.spec.js
 PASS   test  src/scripts/vuejs/store/modules/plan/__tests__/actions.spec.js
 PASS   test  src/scripts/vuejs/components/plan/__tests__/PlanTitle.spec.js
 PASS   test  src/scripts/vuejs/store/modules/plan/__tests__/getters.spec.js
 PASS   test  src/scripts/tests/specs/test.spec.js
 PASS   test  src/scripts/vuejs/components/plan/__tests__/PlanSelect.spec.js
 PASS   test  src/scripts/vuejs/components/plan/__tests__/PlanLeftNavPanel.spec.js

Test Suites: 9 passed, 9 total
Tests:       42 passed, 42 total
Snapshots:   0 total
Time:        5.301s
Ran all test suites.
[info] "2019-09-05T20:31:00.211Z"  'Started with: token ["xxxxxxxxxxxxx"], accountToken [undefined], username [undefined], projectName [undefined], commitId [undefined], language [undefined], endpoint [undefined], format [undefined], path prefix [undefined], verbose [true], debug [undefined]'
[info] "2019-09-05T20:31:00.224Z"  'Handling input for: token ["xxxxxxxxxxxxx"], accountToken [undefined], username [undefined], projectName [undefined], commitId [undefined], language [undefined], endpoint [undefined], format ["lcov"], path prefix [""], verbose [true], debug [undefined]
'
[debug] "2019-09-05T20:31:00.229Z"  'Parsing Lcov Data'
[debug] "2019-09-05T20:31:00.302Z"  'Successfully Parsed Lcov Data'
[debug] "2019-09-05T20:31:00.308Z"  'Sending coverage'
[error] "2019-09-05T20:31:01.360Z"  'Status Code [404] - Error [{"error":"not found"}]'
[error] "2019-09-05T20:31:01.363Z"  'Error sending coverage'
[error] "2019-09-05T20:31:01.381Z"  Error: Expected Successful Status Code, but got [404]
    at C:\src\projectx\node_modules\codacy-coverage\lib\reporter.js:110:23
    at tryCatcher (C:\src\projectx\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\src\projectx\node_modules\bluebird\js\release\promise.js:517:31)
    at Promise._settlePromise (C:\src\projectx\node_modules\bluebird\js\release\promise.js:574:18)
    at Promise._settlePromise0 (C:\src\projectx\node_modules\bluebird\js\release\promise.js:619:10)
    at Promise._settlePromises (C:\src\projectx\node_modules\bluebird\js\release\promise.js:695:18)
    at _drainQueueStep (C:\src\projectx\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\src\projectx\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\src\projectx\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\src\projectx\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Any Help?

**Comment by ljmf00** [comment]
Hey @ddieppa ,

I was trying to replicate your issue, can you check if:
- Your enterprise URL is valid and doesn't have any `/` at the end.
- Your project token is valid (via `--token` or `CODACY_PROJECT_TOKEN` environment variable)

Thanks,
Luis

**Comment by ddieppa** [comment]
yes, the URL is valid and the token is via an env variable, and it is correct too

**Comment by ljmf00** [comment]
Hi @ddieppa ,

Can you please reach out to support@codacy.com with this report?

Thanks,
Luís
